version: "3"

services:

  notebook:
    build: zeppelin
    ports:
      - 8080:8080
    volumes:
      - ./zeppelin/logs:/logs
      - ./zeppelin/notebook:/notebook
    environment:
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
  
  hivedb:  # Do not change this name, it is used in the address with the Zeppelin connector interpreter.
    build: hivedb
    ports:
      - 10000:10000
      - 10002:10002
    volumes:
      - ./hivedb/shared_data:/opt/data
    environment:
      - SERVICE_NAME=hiveserver2
      


  

